### ISSUE TITLE
Homebrew formula

### ISSUE THREAD

**Issue by gfontenot** [iljaiwas/objc-run#7]
I would love to be able to install this via Homebrew instead of having to install this in my path manually. This is painfully simple for a shell script like this, but you'll have to start tagging release versions. Here's an example formula that you could use:

``` ruby
require 'formula'

class ObjcRun < Formula
  homepage 'https://github.com/iljaiwas/objc-run'
  url 'https://github.com/iljaiwas/objc-run.git', :tag => '1.0'
  head 'https://github.com/iljaiwas/objc-run.git'

  def install
    bin.install 'objc-run'
  end
end
```

**Comment by mmorey** [comment]
:+1:

**Comment by iljaiwas** [comment]
I added a "1.0" tag to the current revision. Does this help?

**Comment by gfontenot** [comment]
Sure does! Do you want to submit a PR to the homebrew repo, or do you
want me to?

On 01/10, Ilja Iwas wrote:

> I added a "1.0" tag to the current revision. Does this help?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/iljaiwas/objc-run/issues/7#issuecomment-32066410

## 

Gordon Fontenot
iOS developer at thoughtbot
http://www.thoughtbot.com
@gfontenot

**Comment by iljaiwas** [comment]
I don't have a clue about homebrew, so I'd appreciate it if you could take the time to submit the formula. Thanks.

**Comment by gfontenot** [comment]
Will do.

On 01/10, Ilja Iwas wrote:

> I don't have a clue about homebrew, so I'd appreciate it if you could take the time to submit the formula. Thanks.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/iljaiwas/objc-run/issues/7#issuecomment-32072122

## 

Gordon Fontenot
iOS developer at thoughtbot
http://www.thoughtbot.com
@gfontenot

**Comment by postmechanical** [comment]
Thanks for doing this!

**Comment by gfontenot** [comment]
@iljaiwas Can you either move the `1.0` tag to the current `HEAD`, or add a new tag? That way I can include the tests in the brew formula.

**Comment by iljaiwas** [comment]
Current HEAD is now tagged as 1.1. Hope this helps.

**Comment by iljaiwas** [comment]
Pull request for home brew is currently open at: https://github.com/Homebrew/homebrew/pull/26052

**Comment by gfontenot** [comment]
I actually opened a PR for this 9 days ago: Homebrew/homebrew#25814. I started getting the runaround from them, and haven't had time to figure out how to do what they are asking me to do. Mine might be a better starting point if someone wants to lend a hand.

**Comment by iljaiwas** [comment]
I see. I'll ask @afh to help us out.

**Comment by iljaiwas** [comment]
Formula pull request is approved now. Thanks everyone for helping out.
